# Generated by Django 3.2.25 on 2025-02-20 17:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [
        ("exams", "0010_add_exam_report_visibility_field"),
        ("exams", "0011_update_exam_report_visibility_field"),
    ]

    dependencies = [
        ("exams", "0009_alter_exam_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftexam",
            name="instant_report_visibility",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="instant_report_visibility",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
